"""
screens.py -- Stage 1: atmospheric phase-screen generation.

Screens are generated by aotools
(aotools.turbulence.phasescreen.ft_phase_screen): a finite, static, STRICTLY
PERIODIC von Karman screen built from (r0, N, delta, L0, l0, seed) by the
McGlamery/Schmidt FFT method.

Fixed architecture (do not change here):
  * We do NOT write a from-scratch screen generator, and we do NOT use the
    aotools infinite-screen classes (PhaseScreenVonKarman). Taylor's
    frozen-flow hypothesis requires a rigid STATIC screen translated across the
    aperture; infinite/renewing screens violate frozen flow.
  * NO subharmonics and NO oversampling. Both break the strict periodicity of
    the FFT screen, and the split-step angular-spectrum kernel (Stage 2) is
    itself periodic -- a non-periodic screen makes the kernel diffract the
    wrap-seam and inject a spurious scintillation offset (~+0.073 was seen with
    the retired generator). The price of strict periodicity is a known
    low-frequency (large-separation) deficit in the structure function, which
    is measured and documented in verify_screens.py.

Equation ledger: PROCESS.md. Reference keys used in comments:
    [Schmidt] J. D. Schmidt, "Numerical Simulation of Optical Wave Propagation
              with Examples in MATLAB", SPIE Press, 2010.
    [AP]      L. C. Andrews & R. L. Phillips, "Laser Beam Propagation through
              Random Media", 2nd ed., SPIE Press, 2005.
    [aotools] aotools 1.0.7, aotools.turbulence (Townson et al., Optics
              Express 27, 31316, 2019).

Environment: gnuradio-env, numpy < 2, aotools 1.0.7. Phase is real-valued.
"""

import numpy as np
from aotools.turbulence.phasescreen import ft_phase_screen


# Kolmogorov-limit von Karman scales used for the Stage-2 Rytov verification:
# push the finite-L0 von Karman spectrum into the Kolmogorov inertial range so
# that sigma_R^2 = 1.23 Cn^2 k^(7/6) L^(11/6) is the correct analytic target.
# l0 MUST be > 0 because aotools computes fm = 5.92/l0; a literal 0 raises
# ZeroDivisionError. 1e-6 m is far below any grid pitch, so it is effectively
# zero inner scale. (PROCESS.md, Stage 1 / Stage 2.)
KOLMOGOROV_L0 = 1.0e6      # m, effectively infinite outer scale
KOLMOGOROV_l0 = 1.0e-6     # m, effectively zero inner scale (must be > 0)


def generate_screen(r0, N, delta, L0, l0, seed=None):
    """One real phase screen [rad] with von Karman statistics, via aotools.

    Strictly periodic (FFT method, no subharmonics/oversampling). The returned
    array is N x N, each element a phase in radians.

    Parameters
    ----------
    r0    : float, Fried parameter of THIS screen [m]
    N     : int,   grid size [pixels]
    delta : float, pixel pitch [m]
    L0    : float, outer scale [m]
    l0    : float, inner scale [m] (must be > 0; aotools computes 5.92/l0)
    seed  : int or None, RNG seed for a deterministic screen
    """
    if l0 <= 0.0:
        raise ValueError(
            "l0 must be > 0 (aotools computes 5.92/l0); use a tiny l0 such as "
            "%g for the Kolmogorov limit" % KOLMOGOROV_l0)
    phs = ft_phase_screen(float(r0), int(N), float(delta), float(L0),
                          float(l0), seed=seed)
    phs = np.asarray(phs, dtype=np.float64)
    assert np.isrealobj(phs) and np.all(np.isfinite(phs)), \
        "phase screen must be real and finite"
    return phs


def empirical_structure_function(screen, delta, max_sep_px):
    """Isotropic empirical phase structure function D(r) of a PERIODIC screen.

        D(r) = < [phi(x + r) - phi(x)]^2 >

    averaged over the full grid (np.roll is an exact circular shift, valid
    because the FFT screen is periodic) and over the x and y directions.

    Returns (sep_m, D) with sep_m = (1..max_sep_px) * delta [m], D in rad^2.
    """
    seps_px = np.arange(1, int(max_sep_px) + 1)
    D = np.empty(seps_px.size, dtype=np.float64)
    for i, s in enumerate(seps_px):
        dphi_x = np.roll(screen, -int(s), axis=0) - screen
        dphi_y = np.roll(screen, -int(s), axis=1) - screen
        D[i] = 0.5 * (np.mean(dphi_x * dphi_x) + np.mean(dphi_y * dphi_y))
    return seps_px * delta, D


def ensemble_structure_function(r0, N, delta, L0, l0, n_realizations,
                                max_sep_px, base_seed=0):
    """Empirical structure function averaged over an ensemble of independent
    screens (distinct seeds), to suppress realization noise."""
    acc = None
    sep_m = None
    for j in range(int(n_realizations)):
        scr = generate_screen(r0, N, delta, L0, l0, seed=base_seed + j)
        sep_m, D = empirical_structure_function(scr, delta, max_sep_px)
        acc = D if acc is None else acc + D
    return sep_m, acc / float(n_realizations)
